### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by harshmunshi** [lukeremy/vehicle_detection#1]
I tried to run the main file and it returns the following error.

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import _main_init
  File "/home/harsh/Tracking/vehicle_detection/_main_init.py", line 9, in <module>
    from _preview_init import PreviewInit
  File "/home/harsh/Tracking/vehicle_detection/_preview_init.py", line 10, in <module>
    preview_ui = uic.loadUiType("gtk/preview.ui")[0]
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/__init__.py", line 208, in loadUiType
    winfo = compiler.UICompiler().compileUi(uifile, code_string, from_imports, resource_suffix)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/Compiler/compiler.py", line 140, in compileUi
    w = self.parse(input_stream, resource_suffix)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/uiparser.py", line 974, in parse
    document = parse(filename)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: 'gtk/preview.ui'

Kindly Help

**Comment by lukeremy** [comment]
Are you still working on this harshmunshi?
